### ISSUE TITLE
Critical error - Addon can't load with new WildStar version

### ISSUE THREAD

**Issue by vdubus** [indigotock/WeightMate#8]
Error :
...ing\NCSOFT\WildStar\Addons\WeightMate\WeightMate.lua:17: attempt to index field 'CodeEnumSigilType' (a nil value)
stack trace:
...ing\NCSOFT\WildStar\Addons\WeightMate\WeightMate.lua:17: in main chunk

The problem is the use of "CodeEnumSigilType" which should be replaced by "CodeEnumRuneType".

**Comment by indigotock** [comment]
Ha. It's been so long, that I forgot this was an issue when I fixed it (in cb8a20f). CurseForge has finally accepted the uploaded file, so if you are still interested, then update and play!
